version: '3.8'

services:
  # MySQL Database
  mysql:
    image: 'bitnami/mysql:8.0'
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: Admin@123
    ports:
      - '3308:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  # MongoDB Database
  mongodb:
    image: 'bitnami/mongodb:8.0.1'
    container_name: mongodb
    hostname: mongodb
    environment:
      MONGODB_ROOT_USERNAME: root
      MONGODB_ROOT_PASSWORD: Admin@123
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  # Kafka
  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://35.192.34.244:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - app_network

  # Eureka Server
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    hostname: eureka-server
    ports:
      - '8761:8761'
    environment:
      - EUREKA_SERVER_PORT=8761
    depends_on:
      - kafka
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
  mongo_data:
